# Azure Pipelines - zmodyfikowany pipeline z pytest i backupem

trigger:
  paths:
    include:
      - src/**
      - tests/**

pool:
  name: PPPool

steps:
- script: |
    python -m pip install --upgrade pip
    pip install pytest
  displayName: 'Install dependencies'

- script: |
    pytest tests/test_kalkulator.py
  displayName: 'Run pytest'

- script: |
    if not exist backup mkdir backup
    copy src\metody.py backup\
  displayName: 'Backup metody.py (Windows CMD)'


